name: Continuous Integration

# Only run CI on Pull Requests
on: pull-request

jobs:

  lint:

    runs-on: ubuntu-latest

    # TODO(python3): Include 3.7 and 3.8
    strategy:
      python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Install Python Dependencies
        run: python -m pip install black flake8
      - name: Check Python formatting with Black
        run: black --line-length 100 --target-version py36 --check --diff .
      - name: Verify Python files using Flake8
        run: flake8 --max-line-length=100 .


