name: Continuous Integration

# Only run CI on Pull Requests
on: pull_request

jobs:

  lint:
    name: Python Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: python -m pip install black flake8

      - name: Check Python formatting with Black
        run: black --line-length 100 --target-version py36 --check --diff .

      - name: Verify Python files using Flake8
        run: flake8 --max-line-length=100 --count --statistics --exit-zero .

  build:      
    name: Verify Dockerfiles
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build .
